accounts:
  datasource:
    url: jdbc:mysql://gymapp.socom.pl:3306/gymappso_kodillatest?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: gymappso_kodillatest
    password: testtest
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update
  allow-get-accounts: true
  server:
    port: 7777

customer:
  datasource:
    url: jdbc:mysql://gymapp.socom.pl:3306/gymappso_kodillatest?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: gymappso_kodillatest
    password: testtest
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update
  server:
    port: 7778

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
