accounts:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://gymapp.socom.pl:3306/gymappso_kodillatest?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: gymappso_kodillatest
    password: testtest
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: create-drop
  allow-get-accounts: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

server:
  port: 7777
